server:
  port: ${PORT:8819}
  servlet:    context-path: /auth
spring:
  application:
    name: csk-service-ucenter-auth
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect    hibernate:      ddl-auto: update
    show-sql: true
  redis:    host: ${REDIS_HOST:127.0.0.1}
    port: ${PORT:6379}
    timeout: 5000 #连接超时：毫秒
    jedis:      pool:
        max-active: 3        max-idle: 3
        min-idle: 1
        max-wait: -1  #连接池最大等待时间 -1无限制
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/chuanshuke?useUnicode=true&characterEncoding=utf-8&useSSL=false      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: root
      initialSize: 5  #初始建立连接数量
      minIdle: 5  #最小连接数量
      maxActive: 20 #最大连接数量
      maxWait: 10000  #获取连接最大等待时间，毫秒
      testOnBorrow: true #申请连接时检测连接是否有效
      testOnReturn: false #归还连接时检测连接是否有效
      timeBetweenEvictionRunsMillis: 60000 #配置间隔检测连接是否有效的时间（单位是毫秒）
      minEvictableIdleTimeMillis: 300000  #连接在连接池的最小生存时间（毫秒）
auth:
  tokenValiditySeconds: 1200 #token存储到redis的过期时间
  clientId: CskWebApp
  clientSecret: CskWebApp
  cookieDomain: localhost #java.chuanshuke.com
  cookieMaxAge: -1
encrypt:
  key-store:
    location: classpath:/csk.keystore
    secret: chuanshukekeystore
    alias: cskkey
    password: chuanshuke
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:      defaultZone: ${EUREKA_SERVER:http://eureka01:8761/eureka/} #http://localhost:8762/eureka/}  instance:
    prefer-ip-address: true
    ip-address: ${IP_ADDRESS:127.0.0.1} 
    instance-id: ${spring.application.name}:${server.port}