server:
  port: 8853
  servlet:    context-path: /api
spring:
  application:    name: csk-govern-gateway
  redis:    host: ${REDIS_HOST:127.0.0.1}
    port: ${REDIS_PORT:6379}
    timeout: 5000  #连接超时  毫秒
    jedis:      pool:        max-active: 3
        max-idle: 3
        min-idle: 1
        max-wait: -1  #连接池最大等待时间 -1没有限制
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:      defaultZone: ${EUREKA_SERVER:http://eureka01:8761/eureka/}
  instance:    prefer-ip-address: true  #将自己的IP地址注册到eureka服务中
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}  #指定实例+端口
ribbon:
  MaxAutoRetries: 2  #最大重试次数，当eureka中可以找到服务，但是服务连接不上时将会重试，如果eureka中找不到服务则直接走断路器
  MaxAutoRetriesNextServer: 3  #切换实例的重试次数
  OkToRetryOnAllOperations: false  #对所有操作请求都进行重试，如果是get则可以，如果是post，put等操作没有实现幂等的情况下是很危险的所以设置为false
  ConnectTimeout: 5000  #请求连接的超时时间
  ReadTimeout: 6000  #请求处理的超时时间zuul:
  routes:
    manage-cms:
      path: /cms/**
      service-id: csk-service-manage-cms
      strip-prefix: false
      sensitive-headers: 
    service-ucenter:
      path: /ucenter/**
      service-id: csk-service-ucenter
      strip-prefix: false
      sensitive-headers: 
    service-portal:
      path: /portal/**
      service-id: csk-service-portal
      strip-prefix: false
      sensitive-headers: 
    service-ucenter-auth:
      path: /auth/**
      service-id: csk-service-ucenter-auth
      strip-prefix: false
      sensitive-headers: 
    service-search:
      path: /search/**
      service-id: csk-service-search
      strip-prefix: false