server:
  port: ${PORT:8854}
mybatis:  configuration:    map-underscore-to-camel-case: true #表中字段含下划线，自动启用驼峰原则
spring:
  application:
    name: csk-service-portal
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect    hibernate:      ddl-auto: update
    show-sql: true
  redis:
    host: ${REDIS_HOST:127.0.0.1}
    port: ${REDIS_PORT:6379}
    timeout: 5000 #连接超时 毫秒
    jedis:
      pool:
        maxActive: 3
        maxIdle: 3
        minIdle: 1
        maxWait: -1 #连接池最大等行时间 -1没有限制
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/chuanshuke?useUnicode=true&characterEncoding=utf-8&useSSL=false      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: root
      initialSize: 5  #初始建立连接数量
      minIdle: 5  #最小连接数量
      maxActive: 20 #最大连接数量
      maxWait: 10000  #获取连接最大等待时间，毫秒
      testOnBorrow: true #申请连接时检测连接是否有效
      testOnReturn: false #归还连接时检测连接是否有效
      timeBetweenEvictionRunsMillis: 60000 #配置间隔检测连接是否有效的时间（单位是毫秒）
      minEvictableIdleTimeMillis: 300000  #连接在连接池的最小生存时间（毫秒）
pagehelper:
  helper-dialect: mysql
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:      defaultZone: ${EUREKA_SERVER:http://eureka01:8761/eureka/} #http://localhost:8762/eureka/}  instance:
    prefer-ip-address: true
    ip-address: ${IP_ADDRESS:127.0.0.1} 
    instance-id: ${spring.application.name}:${server.port}    